### ISSUE TITLE
Whitescreen after login in 2 times

### ISSUE THREAD

**Issue by x2hunter** [ShipBit/wingman-ai#149]
logged in with google, chose my name in the app, then used the app it worked perfectly, then when I clicked on my account again, it showed my name again and well when I continued the app is just completely white now and wont do anything, I even reinstalled it.

**Comment by Shackless** [comment]
Yes, this is the single worst known issue we have right now. The workaround is:

-close Wingman
- delete %LOCALAPPDATA%\com.wingman.dev
- Start the client again
