### ISSUE TITLE
Provide releases using GitHub actions and sign the damn exe

### ISSUE THREAD

**Issue by Shackless** [ShipBit/wingman-ai#17]
We already have a GitHub action that bundles and builds releases using `pyinstaller`. There are a couple of things that need clarification: 

- OV or EV certificate to sign the Windows executable?
- How to best add ffmpeg to the release packages? bash script with a curl command? Add to zip? Installer? 
- Can we provide symlinks inside of our release zip pointing to `/_internal/config.yaml` and `/_internal/wingman`?

If somebody knows more about these topics, please contact me. Thank you!

**Comment by umbah** [comment]
EV certificates are only issued to companies, you'll have to use an OV certificate and build reputation over time for Windows SmartScreen filter to recognize the signed apps as safe.

You can't distribute symlinks inside .zip files on Windows. No idea about the ffmpeg thing

**Comment by Shackless** [comment]
We are a company and have already ordered an EV certificate and are waiting for it to arrive. We also got rid of the ffmpeg dependencies for our next version. I'll close this issue once we have the published the release. Thank you.

**Comment by Shackless** [comment]
will be fixed in the next release
