### ISSUE TITLE
Can't get a .Vue or a .sh file to work with Wingman

### ISSUE THREAD

**Issue by Nerding4life** [ShipBit/wingman-ai#170]
Seems to be that .vue(Vue 2 Framework) or .sh(Linux bash) files do not work with Wingman. The script is just running over them, and not doing a thing. Is this something that has not been built into your system to work with these files, or have we broken it? We are running it in VSCode

**Comment by Shackless** [comment]
What exactly are you trying to do and what has Vue to do with it? 😉

**Comment by Nerding4life** [comment]
It runs over the rest of our files/code just fine(.php, .html, .js, .json, .sql, etc), but completely skips the vue and bash files that we have. We are trying to use wingman with ollama.

**Comment by Shackless** [comment]
What exactly do you mean by "running over the files"? Wingman AI is a framework to utilize speech io to interact with LLMs. Are you maybe in the wrong repository?

**Comment by Nerding4life** [comment]
When we run this in a php file, we get nice code response, in form of greyed out code and the loading circle in the bottom right hand of the screen, from the ai, and in a vue file it does not return any code, and does not show the loading circle at all.
Thank you for helping here.

**Comment by Nerding4life** [comment]
You would be correct! We should be in https://github.com/RussellCanfield/wingman-ai 

Thanks for your help anyway!

**Comment by Shackless** [comment]
You're welcome... lol
