### ISSUE TITLE
Add timer commands to `OpenAiWingman` class

### ISSUE THREAD

**Issue by Cr45hCode** [ShipBit/wingman-ai#21]
Timer commands are like delayed functions. Instead of doing an action right now, the AI would respond now and start a timer, running for a certain amount of time, which triggers another command when finished.
This would allow the AI to _"remind the user in 1h to take a break"_, or _"turn the lights back on in 5 minutes"_.

It still would not solves "reminding the user to say happy birthday to mum, every year on her birthday", but it's a start.

**Comment by Shackless** [comment]
@SawPsyder has this covered with a skill that will be available soon (tm)
