### ISSUE TITLE
Wrong language detected and wrong response language

### ISSUE THREAD

**Issue by danielduckworth** [ShipBit/wingman-ai#226]
When I speak in English, I get a Chinese response.
![Screenshot 2024-07-16 070434](https://github.com/user-attachments/assets/4105864d-6df8-48be-b75d-8956bf40dc65)

**Comment by teddybear082** [comment]
can you share your settings for speech to text? I see it seems like its translating your voice too.  Also, does it do this all the time or it was just this session?

**Comment by Shackless** [comment]
please create a Thead in our #support Discord channel. If we come to the conclusion that there is a bug, we'll create an issue here but I'm 99.9% certain that this is a misconfiguration. Thank you.
