### ISSUE TITLE
500 Internal Error on Start Page

### ISSUE THREAD

**Issue by Jerry0022** [ShipBit/wingman-ai#242]
Hey, 

I guess I made something wrong, creating a new folder for Star Citizen (as the default one) and then deleted it and accidentally as well the default folder. 
I tried to reinstall, reboot, but no help...
Unfortunately now I get only this error on the start page:

![image](https://github.com/user-attachments/assets/bccc9cbf-a5a0-4021-b5a6-a52dc1f12ead)

**Comment by Shackless** [comment]
Hi, we offer support for Wingman on our [Discord server](https://discord.gg/k8tTBar3gZ), no here on GitHub. Please join and ask your question in the #support channel. Thank you.
