### ISSUE TITLE
Check keyboard localisation in pydirectinput

### ISSUE THREAD

**Issue by Shackless** [ShipBit/wingman-ai#25]
Quoted from Discord: 

> I have been unable to make any command using the num# keys work. Everything is correctly ordered and aligned, the AI seems to think it's working, but the keypress is not registered. Pressing manually works as expected.

My guess is that [pydirectinput](https://pypi.org/project/PyDirectInput/) might not be aware of localisation and non-English keyboard layouts. This might not just affect num-keys.

**Comment by Shackless** [comment]
Doesn't seem to work with German keyboards and "pagedown", for example.

**Comment by Joney0210** [comment]
my windows is windows10, use chinese keyborad layout.
I'm try modifier Ctrlright, and num0 - num9, not work, look like WingmanAI not sent out hotkey.

**Comment by Shackless** [comment]
We'll use a new library in beta2 that supports both OSX and Windows and will be able to record keys (if using our upcoming new client). This should take care of these problems.
