### ISSUE TITLE
Check unreadable chars in ai context

### ISSUE THREAD

**Issue by memidgety** [ShipBit/wingman-ai#63]
![Error_char](https://github.com/ShipBit/wingman-ai/assets/596278/c26a87fc-4954-4101-ba51-8cb573cdb896)
[config_eel.txt](https://github.com/ShipBit/wingman-ai/files/13551543/config_eel.txt)

Uploaded config as a txt since github doesnt support yaml

This is the file in question. You will notice that the context for the board-computer is fine, but it throws the error seen above. I rewrote the context and it worked.

For situational context: This is a config someone from the discord sent me to test/fix. So the file came from him. He stated to be using a regular keyboard, so we don't know what character could have been an issue.

**Comment by Shackless** [comment]
This config uses a mix of `TAB` and `SPACE` characters for indentation. 

This is correct and working:

![CleanShot 2023-12-05 at 15 38 22@2x](https://github.com/ShipBit/wingman-ai/assets/306996/0a9ffe1c-5c21-4b44-b045-3f3dd2cb8555)

The broken section looks like this: 

![CleanShot 2023-12-05 at 15 39 36@2x](https://github.com/ShipBit/wingman-ai/assets/306996/553613e2-ec6e-42cd-8ba2-6ff1ece49b09)

I don't think this is something we can control as long as we have to edit the config manually with different editors etc.
