### ISSUE TITLE
Avast identifies virus

### ISSUE THREAD

**Issue by BjornB2** [ShipBit/wingman-ai#72]
Avast seems to think there is a virus in WingmanAI.exe:

![Naamloos](https://github.com/ShipBit/wingman-ai/assets/3328086/fc71c45a-161e-4bb1-9d03-c18454ee8efa)

**Comment by Shackless** [comment]
Yes, it's a false positive. Technically speaking, Wingman is a "keylogger" as it listens to the global push-to-talk keys. It doesn't help that the `.exe` is only self-signed. We need an EV certificate which is complicated, expensive and does not work well with our serverless CI/CD infrastructure. For now, you have to ignore it or turn it off, sorry.

**Comment by Zer0Squared** [comment]
OMG.  Ok, I was getting an "unable to set file attribute" when trying to unzip this exe using every unzip program I had and this was the issue the whole time for me.
Thanks for posting this!

**Comment by Shackless** [comment]
Will be fixed in the next release
