### ISSUE TITLE
WingmanAI does not set its working dir correctly when exe is launched from startmenu

### ISSUE THREAD

**Issue by SawPsyder** [ShipBit/wingman-ai#86]
When the WingmanAICore.exe is launched from start menu (not a shortcut, but the exe) it runs into errors trying to create the mic recording and folder:
```ERROR:pynput.keyboard.Listener:Unhandled exception in listener callback
Traceback (most recent call last):
  File "pynput\_util\__init__.py", line 228, in inner
  File "pynput\keyboard\_win32.py", line 290, in _process
  File "pynput\_util\__init__.py", line 144, in inner
  File "main.py", line 58, in on_release
  File "services\audio_recorder.py", line 49, in stop_recording
    os.makedirs("audio_output")
  File "<frozen os>", line 225, in makedirs
PermissionError: [WinError 5] Zugriff verweigert: 'audio_output'
```

Probably on start, it should just switch to the dir of the exe?
In my uexcorp wingman (because I also create files), I solved it with this code:
```os.path.dirname(os.path.abspath(sys.argv[0]))```
This gives me the `WingmanAICore.exe` path reliably.

So either adjust all creations of folders or switch dir on start?
Not sure about the best solution, but you will figure it out 🙂

Discord Bug report: https://discord.com/channels/1173573578604687360/1185572510075453471

**Comment by Shackless** [comment]
@SawPsyder Could you try with the attached branch? That should do it.
