### ISSUE TITLE
Edge TTS language detection does not work with pure azure configurations

### ISSUE THREAD

**Issue by SawPsyder** [ShipBit/wingman-ai#95]
The automated edge_tts language detection does not work with azure-only configurated wingmen, as it ignores the azure configuration and always uses direct OpenAI calls.

For example comparing `__ask_gpt_for_locale` and `_summarize_function_calls` methods in `open_ai_wingman.py` shows the missing azure "overwrite".
![image](https://github.com/ShipBit/wingman-ai/assets/44277746/779ea03b-37dc-4b4c-9e7a-f2132df6f88b)
![image](https://github.com/ShipBit/wingman-ai/assets/44277746/3690728f-d74d-48fa-bf9b-af82416460f2)

Discord bug report: https://discord.com/channels/1173573578604687360/1188640947358146600

**Comment by Shackless** [comment]
We decided to remove language detection for EdgeTTS entirely. It was only a Wingman-specific workaround with a lot of caveats and no real benefit. Nobody wants a random voice...
This will no longer be an issue in Beta2 and has already been fixed (=removed) on the linked branch
